### ISSUE TITLE
Automatically send email when node is offline longer than x months.

### ISSUE THREAD

**Issue by ohrensessel** [freifunkhamburg/ffffng#25]
It would be nice if the system automatically could send mails to nodes that are offline longer than x months (e.g. 3), asking them to confirm that their data (vpn key, email, coordinates) can be deleted or to deny that.

Maybe that would help in reducing the amount of never-coming-back nodes in the system.

**Comment by baldo** [comment]
I like that thought though we have to keep in mind that we don't have an opt-in for every node for automated emails. We must really make sure not to spam people that haven't opted-in.

**Comment by rubo77** [comment]
So do we need an extra field in the Form, where they can opt-in?

**Comment by baldo** [comment]
This would increase complexity quite alot. The form should imho be as simple to use as possible. This would also mean alot of effort to develop where I don't see the real benefit (we have the monitoring feature that people can use). Closing for now.
