### ISSUE TITLE
Speicherzeitraum vom User abnicken

### ISSUE THREAD

**Issue by rubo77** [freifunkhamburg/ffffng#35]
Es muss eigentlich ein Häkchen gesetzt werden, dass man damit einverstanden ist, dass die Daten lokal gespeichert werden, in dem Zuge sollten wir auch gleich den User selbst entscheidenlassen, wie lange seine Daten aufbewahrt werden, wenn der Knoten offline ist.

Z.B. bei Events die Jährlich auftreten, ist es notwendig, dass der Key nach einem Jahr noch funktioniert, damit sich die Knoten automatisch updaten können, auch wenn die Knoten das ganze Jahr über offline sind.

Wohingegen z.B. bei tTestknoten, die Daten ein paar tage nach nicht-mehr-gebrauch gelöscht werden können.

- [ ] Ich bin damit einverstanden, dass meine Daten intern gespeichert werden, solange mein Knoten sich regelmässig am Freifunk Netz anmeldet und solange die Daten nach [  `   <positive_int>   ` ] Tagen/Monaten/Jahren Inaktivität gelöscht werden

**Comment by baldo** [comment]
Finde das übertrieben. Durch das Monitoring hat der Nutzer die Möglichkeit, sich benachrichtigen zu lassen, wenn sein Knoten offline ist. Für die handvoll Edge-Cases finde ich den Aufwand und die Komplexität sowohl im UI als auch im Code übertrieben. Die Sache mit dem Häkchen ist insofern überflüssig, dass der Nutzer ja explizit die Daten eingibt, die gespeichert werden sollen und z. B. bei den Kontaktdaten auch explizit über die Verwendung informiert wird. Imho sollte das Formular so einfach wie möglich gehalten werden.

**Comment by rubo77** [comment]
Wie handhaben wir denn dann user, die Ihre Knoten absichtlich 1 Jahr offfline haben wollen ohne diese neu registrieren zu müssen?

**Comment by rubo77** [comment]
Ich hatte diesen Request so gedacht, dass man vor allem den Wert, wie lange seine daten nach dem nicht-gebrauch gespeichert werden sollen selbst bestimmen können sollte.

**Comment by baldo** [comment]
Finde ich für den Edge-Case wie gesagt übertrieben und schlecht für die Usability. Im Zweifel kopiert man halt händisch die Dateien beiseite und nach einem Jahr zurück.

**Comment by rubo77** [comment]
oder n dem Moment, wo ein knoten komplett gelöscht wird noch mal eine email mit den daten, die gelöscht wurden. So ein user, der in feinster kleinarbeit für seine 20 router auf ner convention die koordinaten rausgesucht hat und das ncht wusste, dass die wieder gelöscht wurden, bevor die convention anfängt ist das fatal. 

so eine email wäre doch sicher leicht zu generieren oder? 

im gluon config mode am ende steht ja auch ein link zum formular mit den daten im querystring mit drin

**Comment by baldo** [comment]
Wir haben (leider?) keinen Double-Opt-In für automatisierten Versand, nur beim Monitoring. Für die normale Registrierung von Knoten ohne Monitoring würde ich das auch nicht einbauen wollen, da es eine zusätzliche Hürde darstellt und Nutzer den Bestätiguns-Link auch nicht Klicken müssen (Bearbeitung und Inbetriebnahme sollten imho auch ohne Opt-In funktionieren).

Und die Kontendaten automatisch unverschlüsselt per Mail zu verschicken halte ich für keine gute Idee.

**Comment by rubo77** [comment]
Mit egal, ich denke nur, es ist nicht sinnvoll, engagierte Leute nach 3 Monaten schon aus zu sperren, nur weil die 3 Monate im Urlaub waren oder so.
