### ISSUE TITLE
"du" klein schreiben

### ISSUE THREAD

**Issue by rubo77** [freifunkhamburg/ffffng#36]
Wenn ich das [hier](http://www.duden.de/sprachwissen/sprachratgeber/gross-oder-kleinschreibung-von--em-du-du--em--und--em-ihr-ihr--em--1) richtig interpretiere:

>Nicht großgeschrieben wird auch in Werbeanzeigen bzw. -plakaten, Editorials von Jugendzeitschriften oder in Fragebogen (z. B. bei schriftlich fixierten Prüfungsfragen), da es sich hier jeweils nicht um eine persönliche Anrede handelt.

müsste man in einer Webanwendung alle Du's klein schreiben oder?

**Comment by baldo** [comment]
Joa. Könnte man. Hatte mich bewusst dazu entschieden, überall "Du" groß zu schreiben, da ich es persönlicher finde und wir auf der Seite den Nutzer imho direkt ansprechen. Ist imho ein Grenzfall.
