### ISSUE TITLE
Possibility to send messages to a contact

### ISSUE THREAD

**Issue by rubo77** [freifunkhamburg/ffffng#42]
We need a Form to send messages to certain Node contacts without Revealing the contact

**Comment by baldo** [comment]
We don't have an opt-in for that.

**Comment by rubo77** [comment]
So this means, you don't want add an opt-in to allow to receive messages? Or why it sthis closed?

sounds a good idea to add such an opt-in:

"allow users to send me a message through the form"

(If you just don't have the time, I suggest to leave this open until someone has time to implement it.)

**Comment by baldo** [comment]
You need a double opt-in for that. What would the process look like if the user does not confirm the double opt-in? I don't think it's worth the effort and it would complicate the process of setting up a node from a UX point of view.

**Comment by rubo77** [comment]
You don't need a double opt-in. 

it would be enough to have a button in the settings page that you would like to receive emails.

And then a link at the botom inside the email, that you can unset this option with one klick.
