### ISSUE TITLE
Mixed content warning

### ISSUE THREAD

**Issue by kpcyrd** [freifunkhamburg/ffffng#5]
Our tile provider currently doesn't support https, so we need to load our tiles over http, which triggers a warning on modern browsers.

The tile provider can be changed here: https://github.com/freifunkhamburg/ffffng/blob/master/app/scripts/directives/nodeForm.js#L28

**Comment by baldo** [comment]
The tile provider has been changed. The fix will come with the next major release. This also fixes missing tiles on maximum zoom level.
